In [6]:
!pip install pandas

Collecting pandas
  Downloading pandas-3.0.6-cp314-cp314-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting numpy>=2.3.3 (from pandas)
  Downloading numpy-2.5.4-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.6-cp314-cp314-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 25.9 MB/s  0:00:00m0:00:01
Downloading numpy-2.5.4-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 36.3 MB/s  0:00:006m0:00:01
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]
Successfully installed numpy-2.5.4 pandas-3.0.6

In [7]:
!mamba install requests

import requests
import pandas as pd

indicator = "NY.GDP.MKTP.CD"   # GDP (current US$)
country = "SAU"                # Saudi Arabia

url = f"https://api.worldbank.org/v2/country/{country}/indicator/{indicator}?format=json&per_page=20000"
response = requests.get(url).json()

df = pd.json_normalize(response[1])
df

/bin/bash: line 1: mamba: command not found

,countryiso3code,date,value,unit,obs_status,decimal,indicator.id,indicator.value,country.id,country.value
0,SAU,2025,1.276943e+12,,,0,NY.GDP.MKTP.CD,GDP (current US$),SA,Saudi Arabia
1,SAU,2024,1.254141e+12,,,0,NY.GDP.MKTP.CD,GDP (current US$),SA,Saudi Arabia
2,SAU,2023,1.218585e+12,,,0,NY.GDP.MKTP.CD,GDP (current US$),SA,Saudi Arabia
3,SAU,2022,1.239075e+12,,,0,NY.GDP.MKTP.CD,GDP (current US$),SA,Saudi Arabia
4,SAU,2021,9.826611e+11,,,0,NY.GDP.MKTP.CD,GDP (current US$),SA,Saudi Arabia
...,...,...,...,...,...,...,...,...,...,...
61,SAU,1964,2.371809e+09,,,0,NY.GDP.MKTP.CD,GDP (current US$),SA,Saudi Arabia
62,SAU,1963,2.207393e+09,,,0,NY.GDP.MKTP.CD,GDP (current US$),SA,Saudi Arabia
63,SAU,1962,2.130607e+09,,,0,NY.GDP.MKTP.CD,GDP (current US$),SA,Saudi Arabia
64,SAU,1961,1.920811e+09,,,0,NY.GDP.MKTP.CD,GDP (current US$),SA,Saudi Arabia
65,SAU,1960,1.748124e+09,,,0,NY.GDP.MKTP.CD,GDP (current US$),SA,Saudi Arabia

In [11]:
!pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.9.1-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (9.3 kB)
Requirement already satisfied: numpy>=1.24.1 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from scikit-learn) (2.5.4)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.18.1-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
Collecting joblib>=1.4.0 (from scikit-learn)
  Downloading joblib-1.6.0-py3-none-any.whl.metadata (6.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Downloading narwhals-2.27.1-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Downloading threadpoolctl-3.7.0-py3-none-any.whl.metadata (24 kB)
Collecting cloudpickle>=3.0 (from joblib>=1.4.0->scikit-learn)
  Downloading cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Downloading scikit_learn-1.9.1-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (9.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.2/9.2 MB 22.9 MB/s  0:00:00 eta 0:00:01
Downloading joblib-1.6.0-py3-none-any.whl (306 kB)
Downloading cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Downloading narwhals-2.27.1-py3-none-any.whl (483 kB)
Downloading scipy-1.18.1-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (35.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.3/35.3 MB 36.1 MB/s  0:00:006m0:00:01
Downloading threadpoolctl-3.7.0-py3-none-any.whl (26 kB)
Installing collected packages: threadpoolctl, scipy, narwhals, cloudpickle, joblib, scikit-learn
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6/6 [scikit-learn][0m [scikit-learn]
Successfully installed cloudpickle-3.1.2 joblib-1.6.0 narwhals-2.27.1 scikit-learn-1.9.1 scipy-1.18.1 threadpoolctl-3.7.0

In [12]:
import sklearn

df.sort_values("date")

,countryiso3code,date,value,unit,obs_status,decimal,indicator.id,indicator.value,country.id,country.value
65,SAU,1960,1.748124e+09,,,0,NY.GDP.MKTP.CD,GDP (current US$),SA,Saudi Arabia
64,SAU,1961,1.920811e+09,,,0,NY.GDP.MKTP.CD,GDP (current US$),SA,Saudi Arabia
63,SAU,1962,2.130607e+09,,,0,NY.GDP.MKTP.CD,GDP (current US$),SA,Saudi Arabia
62,SAU,1963,2.207393e+09,,,0,NY.GDP.MKTP.CD,GDP (current US$),SA,Saudi Arabia
61,SAU,1964,2.371809e+09,,,0,NY.GDP.MKTP.CD,GDP (current US$),SA,Saudi Arabia
...,...,...,...,...,...,...,...,...,...,...
4,SAU,2021,9.826611e+11,,,0,NY.GDP.MKTP.CD,GDP (current US$),SA,Saudi Arabia
3,SAU,2022,1.239075e+12,,,0,NY.GDP.MKTP.CD,GDP (current US$),SA,Saudi Arabia
2,SAU,2023,1.218585e+12,,,0,NY.GDP.MKTP.CD,GDP (current US$),SA,Saudi Arabia
1,SAU,2024,1.254141e+12,,,0,NY.GDP.MKTP.CD,GDP (current US$),SA,Saudi Arabia
0,SAU,2025,1.276943e+12,,,0,NY.GDP.MKTP.CD,GDP (current US$),SA,Saudi Arabia

In [13]:
df['date'] = pd.to_datetime(df['date'], format='%Y')
df['date']

0    2025-01-01
1    2024-01-01
2    2023-01-01
3    2022-01-01
4    2021-01-01
        ...
61   1964-01-01
62   1963-01-01
63   1962-01-01
64   1961-01-01
65   1960-01-01
Name: date, Length: 66, dtype: datetime64[us]

In [14]:
df = df.set_index('date')
df

,countryiso3code,value,unit,obs_status,decimal,indicator.id,indicator.value,country.id,country.value
date,,,,,,,,,
2025-01-01,SAU,1.276943e+12,,,0,NY.GDP.MKTP.CD,GDP (current US$),SA,Saudi Arabia
2024-01-01,SAU,1.254141e+12,,,0,NY.GDP.MKTP.CD,GDP (current US$),SA,Saudi Arabia
2023-01-01,SAU,1.218585e+12,,,0,NY.GDP.MKTP.CD,GDP (current US$),SA,Saudi Arabia
2022-01-01,SAU,1.239075e+12,,,0,NY.GDP.MKTP.CD,GDP (current US$),SA,Saudi Arabia
2021-01-01,SAU,9.826611e+11,,,0,NY.GDP.MKTP.CD,GDP (current US$),SA,Saudi Arabia
...,...,...,...,...,...,...,...,...,...
1964-01-01,SAU,2.371809e+09,,,0,NY.GDP.MKTP.CD,GDP (current US$),SA,Saudi Arabia
1963-01-01,SAU,2.207393e+09,,,0,NY.GDP.MKTP.CD,GDP (current US$),SA,Saudi Arabia
1962-01-01,SAU,2.130607e+09,,,0,NY.GDP.MKTP.CD,GDP (current US$),SA,Saudi Arabia
1961-01-01,SAU,1.920811e+09,,,0,NY.GDP.MKTP.CD,GDP (current US$),SA,Saudi Arabia
1960-01-01,SAU,1.748124e+09,,,0,NY.GDP.MKTP.CD,GDP (current US$),SA,Saudi Arabia